# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacionc.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materia', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=120)),
                ('alumnos', models.ManyToManyField(through='asignacionc.Grado', to='asignacionc.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacionc.Materia'),
        ),
    ]
